name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deployment via SSH
    runs-on: ubuntu-latest
    steps:
      - name: SSH Comands to Server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY}}
          args: -tt
          command: cd /home/webdev/Web/maucoding-web-v2 && git pull origin main && pnpm install && pnpm build && pm2 stop mcdg-web-v2 && pm2 start mcdg-web-v2
